version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hz51bhx4441h"
s3_prefix = "resume-backend"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TABLENAME=\"counter-table\" REGIONNAME=\"us-east-2\" AWSENVNAME=\"AWS\""
image_repositories = []
