AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  resume_back-end

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'https://phill.holbrook.cc'"

Parameters:
  TABLENAME:
    Type: String
    Description: The DynamoDB table
    Default: "counter-table"

  REGIONNAME:
    Type: String
    Description: Default region for deployment.
    Default: "us-east-2"

  AWSENVNAME:
    Type: String
    Description: AWS Environment where code is being executed (AWS_SAM_LOCAL or AWS).
    Default: "AWS_SAM_LOCAL"

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: visitor-counter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TABLENAME
      Environment:
        Variables:
          TABLE: !Ref TABLENAME
          REGION: !Ref REGIONNAME
          AWSENV: !Ref AWSENVNAME
      Architectures:
        - x86_64
      Events:
        VisitorCounter:
          Type: Api
          Properties:
            Path: /counter
            Method: get

  CounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: Number
      TableName: !Ref TABLENAME

Outputs:
  VisitorCounterApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Counter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter/"
  VisitorCounterFunction:
    Description: "Visitor Counter Lambda Function ARN"
    Value: !GetAtt VisitorCounterFunction.Arn
  VisitorCounterFunctionIamRole:
    Description: "Implicit IAM Role created for Visitor Counter function"
    Value: !GetAtt VisitorCounterFunctionRole.Arn
